function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 01-Apr-2018 14:40:09

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1);
set(plot1(1),'LineWidth',2);

% Create xlabel
xlabel('Normalised angular frequency ($\omega$)','Interpreter','latex');

% Create ylabel
ylabel('Gain (dB)','Interpreter','latex');

%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-50 0]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',16,'TickLabelInterpreter','latex','XTickLabel',...
    {'0','0.2$\pi$','0.4$\pi$','0.6$\pi$','0.8$\pi$','$\pi$','1.2$\pi$','1.4$\pi$','1.6$\pi$','1.8$\pi$','2$\pi$'});
